### PR TITLE
Howie/healbar3

### PR DESCRIPTION
**Pull request by yuenhol**

### CODE REVIEW

**Review by David-Lam — APPROVED** [review]

**Review by David-Lam — CHANGES_REQUESTED** [review]
Hi Howie. I just notice the pull request merge to dev instead of gamejam branch. Can you change the pr so that it merge to gamejam instead? Thanks.

**Comment by makkamchuen** [comment]
i changed to gamejam branch now

**Review by David-Lam — APPROVED** [review]

**Comment by makkamchuen** [comment]
somehow only the healthbar.meta changes, i am sure it is not what you want, right?

**Review by makkamchuen — COMMENTED** [review]
somehow only the healthbar.meta and prefab changes, is it what you need?

**Pull request closed without merging**
